import { Sparkles } from 'lucide-react';

interface Props {
  tool?: string;
}

export default function AIDisclaimer({ tool }: Props) {
  const msg = tool
    ? `${tool} results are generated by Claude AI using Monash University FODMAP research as its evidence base.`
    : 'Results are generated by Claude AI using Monash University FODMAP research as its evidence base.';
  return (
    <div className="flex items-start gap-2.5 bg-brand-50 border border-brand-200 rounded-xl px-4 py-3">
      <Sparkles className="w-3.5 h-3.5 text-brand-500 flex-shrink-0 mt-0.5" />
      <p className="text-xs text-brand-800 leading-relaxed">
        <strong>AI-generated</strong> — {msg} Results may not be perfectly accurate. Always verify with a qualified dietitian, especially during the reintroduction phase.
      </p>
    </div>
  );
}
