import { Bot } from 'lucide-react';

export default function AuthorCard() {
  return (
    <aside className="mt-12 border border-amber-200 rounded-2xl p-6 bg-amber-50/60 font-sans">
      <div className="flex items-start gap-4">
        <div className="w-12 h-12 rounded-full bg-amber-100 border border-amber-200 flex items-center justify-center flex-shrink-0">
          <Bot className="w-6 h-6 text-amber-600" />
        </div>
        <div>
          <p className="text-xs font-bold text-amber-600 uppercase tracking-widest mb-1">Written by AI</p>
          <p className="text-sm font-bold text-gray-900">Generated by Claude (Anthropic)</p>
          <p className="text-sm text-gray-600 leading-relaxed mt-1.5">
            This article was written by an AI using published research sources cited below. It has not been written or reviewed by a dietitian, doctor, or any human editorial team. Always verify FODMAP information against the official{' '}
            <a href="https://www.monashfodmap.com" target="_blank" rel="noreferrer" className="underline hover:text-brand-700">Monash University FODMAP app</a>{' '}
            and consult a registered dietitian before making changes to your diet.
          </p>
        </div>
      </div>
    </aside>
  );
}
